service: bgc-desafio

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  profile: bgcUser
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
        - 's3:GetObject'
      Resource: 'arn:aws:s3:::puppeteer-bucket/*'

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

functions:
  getProducts:
    handler: handler.getProducts
    events:
      - http:
          path: products
          method: get
    environment:
      HEADLESS: true
      TIMEOUT: 60000
    memorySize: 512
    timeout: 30
