service: bgc-desafio

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - states:*
      Resource: '*'

plugins:
  - serverless-step-functions
  - serverless-offline

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

functions:
  webScraper:
    handler: webScraper.webScraper
    environment:
      HEADLESS: true
      TIMEOUT: 60000
    memorySize: 512
    timeout: 30
  createProductDynamo:
    handler: createProductDynamo.createProductDynamo
    timeout: 10
    memorySize: 128
  getProducts:
    handler: getProducts.getProducts
    timeout: 10
    memorySize: 128
    events:
      - http:
          path: getProducts/{category}
          method: GET
          cors: true

stepFunctions:
  stateMachines:
    AmazonWebScraping:
      name: AmazonWebScraping
      definition:
        StartAt: webScraper
        States:
          webScraper:
            Type: Task
            Resource:
              Fn::GetAtt: [webScraper, Arn]
            ResultPath: '$.products'
            Next: createProductDynamo
          createProductDynamo:
            Type: Task
            Resource:
              Fn::GetAtt: [createProductDynamo, Arn]
            Catch:
              - ErrorEquals: [CreateProductError]
                Next: CreateProductError
            End: true
          CreateProductError:
            Type: Pass
            Result: 'Unable to create product on dynamoDB'
            End: true

resources:
  Resources:
    BestsellersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'Bestsellers'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: category
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: category-index
            KeySchema:
              - AttributeName: category
                KeyType: HASH
            Projection:
              ProjectionType: ALL
